/** The site assistant. Structure lives in ChatWidget.tsx; every word is here. */
export const chat = {
  open: "Ask a question",
  close: "Close",
  title: "Ask Deev",
  subtitle: "Answers about our work, our services and the 70% grant.",
  greeting:
    "Ask me anything about what Deev builds, the projects we have shipped or how the Luxembourg SME grant works. For a real enquiry, the contact form is faster.",
  placeholder: "Type your question",
  send: "Send",
  stop: "Stop",
  clear: "Clear this conversation",
  thinking: "Typing",
  suggestions: [
    "What does Deev build?",
    "How does the 70% grant work?",
    "Show me a web app you built",
  ],
  /** Shown once, above the first message. */
  notice:
    "Answers are generated by AI and can be wrong. Please do not type personal or confidential details.",
  noticeLink: "How we handle this",
  errors: {
    busy: "Too many questions at once. Try again in a moment.",
    upstream: "Something went wrong at our end. Please try again, or email contact@deev.lu.",
    offline: "No connection. Check your network and try again.",
    limited: "That is a lot of questions. Take a short break, or email contact@deev.lu.",
    refused: "I would rather not answer that one. Ask me about Deev instead.",
    unavailable: "The assistant is not available right now. Email contact@deev.lu and we will reply.",
  },
};
